spring:
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:56006/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: JdufOBrarUBwPOPgSMMludvYOCPrZdMt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    filter:
      order: 10
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:your_default_secret_key_here_should_be_at_least_32_characters}
  expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 